Pan=500;
uan=100;
niu=0.78;
nm=2000;
Ta=0.08;
Tm=0.6;
ucn=3.5;
Tniu=0;
ian=Pan/uan;
omegaan=(2*pi/60)*nm;
mn=(niu*Pan)/(0.97*omegaan);
alfa=0.1;
mf=alfa*mn;
kf=(alfa*mn)/omegaan;
ms=mn-mf;
en=(mn*omegaan)/ian;
deltau=uan-en;
Ra=deltau/ian;
ke=en/omegaan;
km=mn/ian;
J=(km*ke*Tm)/Ra;
kA=1;
kE=uan/ucn;
kMI=3.5/ian;
kMomega=5/omegaan;
kDC=1;
Tcd1=Tm;
Tf1=0.15*Tcd1;
ku=kE/ke;
komega=(Ra)/(km*ke);
ucninfinit=(omegaan+((Ra)/(km*ke))*ms)/ku;
ucncalculat=ucninfinit-ucn;
kMm=2/ms;
kBC=(komega)/(ku*kDC*kMm);
kPC=(kE/ke)*kMomega;
Tsuma=Ta;
T1=Tm;
sigma=4.3*100;
tr=8.4*Tsuma;
t1=4.7*Tsuma;
yn=0;
kr=1/(2*kPC*Tsuma);

uainfinit=kE*ucn;%relatile(15)
winfinit=ku*ucn+(kBC*ku*kA*kMm)*ms;%toate alea de la infinit
einfinit=ke*winfinit;%de la m.c.c
deltauinfinit=uainfinit-einfinit;
iainfinit=(1/Ra)*deltauinfinit;
uiinfinit=kMI*iainfinit;
uomegainfinit=kMomega*winfinit;
mfinfinit=kf*winfinit;
minfinit=ms+mfinfinit;

La=Ta*Ra;

roots([Ta*Tm Tm 1]);

kxw=0.75;
kxia=0.008;